Remove retry because it errors when compiling on elixir 1.8
```
== Compilation error in file lib/pagerduty_ex.ex ==
** (ArgumentError) invalid syntax, only "retry", "after" and "else" are permitted
    expanding macro: Retry.retry/2
        lib/pagerduty_ex.ex:49: PagerDutyEx.post_with_retry/1
        (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4
        in Kernel.ParallelCompiler.spawn_workers/6
```